//
//  UserAccountBalanceInteractor.swift
//  TesteiOSV2_Rafael_Hieda
//
//  Created by Rafael  Hieda on 10/29/18.
//  Copyright (c) 2018 Rafael Hieda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserAccountBalanceBusinessLogic
{
    func loadRegistry(id : Int)
}

protocol UserAccountBalanceDataStore
{
  //var name: String { get set }
}

class UserAccountBalanceInteractor: UserAccountBalanceBusinessLogic, UserAccountBalanceDataStore
{
    func loadRegistry(id : Int) {
        worker = BankAPIWorker()
        worker?.getAccountBalance(id, completionHandler: { (accountBalance) in
            let accountDetails = accountBalance
            self.presenter?.presentAccountBalance(response: accountDetails)
        })
        
    }
    
  var presenter: UserAccountBalancePresentationLogic?
  var worker: BankAPIWorker?
  
}
