//
//  LoginRouter.swift
//  TesteiOSV2_Rafael_Hieda
//
//  Created by Rafael  Hieda on 10/28/18.
//  Copyright (c) 2018 Rafael Hieda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
}

protocol LoginDataPassing
{
    func passAccountBalance(account : UserAccount)
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
  weak var viewController: LoginViewController?
    func passAccountBalance(account: UserAccount) {
        let accountBalanceController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "UserAccountBalanceViewController") as! UserAccountBalanceViewController
        accountBalanceController.userAccount = account
        viewController?.present(accountBalanceController, animated: true, completion: nil)
    }
}
